### ISSUE TITLE
Should Performance just be a link for MVP

### ISSUE THREAD

**Issue by costanza13** [costanza13/kara-ok-corral#7]
We talked about having a Performance include both the link to the video (or an embed) and a ratings.  It might make the data models too complex to try to get ratings into the MVP.  Should we just go with a simple link to the video of the performance?  That way, Performances won't need their own schema within the Song model, or a Performance typedef.

**Comment by cupcakesprinkle3** [comment]
One idea was that Performance is a link to the video and "reactions" (in the form of replies) to the performance. Is there a way we could get this going for an MVP?

**Comment by costanza13** [comment]
Possibly.  It does add a bit more complexity.  Performance is already part of Song, which is a "reaction" to a Playlist.  But I did make Song its own model, so adding comments/replies/reactions (maybe we _should_ just call it reactions) to it in the way reactions were defined with thoughts would work.  There is also the additional front-end work it requires (a Performance component that displays the link/embed and the Reactions).  Might need to gauge where we are in a coupe of days to make a decision on this.  Let's discuss in our meeting.

**Comment by costanza13** [comment]
I believe the consensus is to build out performances as an independent piece of content (its own model) with a link to the performance on a video site, a privacy (visibility) setting to determine where it can show up in the app, and an associated array of reactions to the performance (Reaction schema within the Performance model).
